#!/bin/bash
git pull
wget https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts -O StevenBlack_hosts
grep -x -v -f Whitelist StevenBlack_hosts > StevenBlack_modified_hosts
git add *
git commit -m "autogenerated commit"
git push origin master
